config:
    send_anonymous_usage_stats: False
    use_colors: True
    partial_parse: True

mybi_dbt_tutorial:
  target: prod

  outputs:
  
    prod:
      type: clickhouse
      host: clickhouse
      port: 8123
      schema: analytics
      threads: 4
  
    # postgres:
    #   type: postgres
    #   host: postgres
    #   port: 5432
    #   user: postgres
    #   pass: postgres
    #   dbname: postgres
    #   schema: public
    #   threads: 4
